- hosts: mhv
  gather_facts: no
  tasks:
    - name: Make sure libvirt is running
      service: name=libvirt-bin state=started

    - name: Restart nova-compute
      service: name=nova-compute state=restarted
